#!/bin/bash
export http_proxy=socks5://127.0.0.1:22222
export https_proxy=socks5://127.0.0.1:22222
#export http_proxy=socks5://127.0.0.1:11111
#export https_proxy=socks5://127.0.0.1:11111
reloadrepo && sudo -E dnf --refresh $@
