#!/bin/bash
services=()
ctrl_type=$(echo $(basename $0) | awk -F- '{print $2}')

find_obfs_service()
{
    services+=(obfs*@*.service)
}

find_kcp_service()
{
    services+=(kcptun*@*.service)
}

find_ss_service()
{
    services+=(ss*@*.service)
}

find_tunnel_service()
{
    services+=(ss-tunnel@*.service)
}

service_ctrl()
{
    systemctl $1 ${services[@]}
}

case ${ctrl_type} in
    all)
        find_obfs_service
        find_kcp_service
        find_ss_service
    ;;
    kcp)
        find_kcp_service
    ;;
    ss)
        find_ss_service
    ;;
    obfs)
        find_obfs_service
    ;;
    tn|tunnel)
        find_tunnel_servic
    ;;
    *)
        echo "No such function: ${ctrl_type}!"
    ;;
esac

case $1 in
    start)
        service_ctrl start
        service_ctrl "status -l"
    ;;
    stop)
        service_ctrl stop
        service_ctrl "status -l"
    ;;
    restart)
        service_ctrl restart
        service_ctrl "status -l"
    ;;
    status)
        service_ctrl "status -l"
    ;;
    *)
        service_ctrl "status -l"
    ;;
esac
