#!/bin/bash
PROXY_ADDR=127.0.0.1:11111
if [ -e ${HOME}/.config/scripts_opts ]; then
    . ${HOME}/.config/scripts_opts
    PROXY_ADDR=${LOCAL_PROXY}
fi
export https_proxy=socks5://${PROXY_ADDR}
export http_proxy=socks5://${PROXY_ADDR}

PROXY="SOCKS5 ${PROXY_ADDR}; SOCKS ${PROXY_ADDR}"
TMP_DIR=$(mktemp -d)

GFWLIST_URL="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"
GFWLIST_RAW=${TMP_DIR}/gfwlist-raw.txt
GFWLIST=${TMP_DIR}/gfwlist.txt

#if wget -c ${GFWLIST_URL} -O ${GFWLIST_RAW} -o /dev/null; then
if curl -o ${GFWLIST_RAW} ${GFWLIST_URL}; then
  if base64 -d ${GFWLIST_RAW} > ${GFWLIST}; then
    if gfwlist2pac -i ${GFWLIST} --precise -f gfwlist.pac -p "${PROXY}"; then
      echo "Succeed!!"
    else
      echo "Failed!!"
    fi
  else
    echo "Failed to decode ${GFWLIST_RAW}"
  fi
else
  echo "Failed to download gfwlist.txt from ${GFWLIST_URL}"
fi
