#!/usr/bin/bash

IP_RULE="fwmark 0x01/0x01  table 100"
IP_ROUTE="local 0.0.0.0/0 dev lo table 100"

start()
{
    # Install xt_REDIRECT
    /usr/sbin/modprobe xt_TPROXY

    # Adding route rules
    /usr/sbin/ip rule  add ${IP_RULE}
    /usr/sbin/ip route add ${IP_ROUTE}

    # Making table
    /usr/sbin/iptables -t mangle -N V2RAY_PRE
    /usr/sbin/iptables -t mangle -A V2RAY_PRE  -m mark --mark 0xaa                              -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_PRE  -m addrtype --dst-type LOCAL,MULTICAST,BROADCAST -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_PRE  -d 10.0.0.0/8                                    -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_PRE  -d 10.4.10.0/23                                  -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_PRE  -d 10.4.88.0/23                                  -j RETURN

    /usr/sbin/iptables -t mangle -A V2RAY_PRE  -p udp -j TPROXY --on-ip 127.0.0.1 --on-port 55555 --tproxy-mark 0x01/0x01
    /usr/sbin/iptables -t mangle -A V2RAY_PRE  -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 55555 --tproxy-mark 0x01/0x01
    /usr/sbin/iptables -t mangle -A PREROUTING -j V2RAY_PRE
    
    /usr/sbin/iptables -t mangle -N V2RAY_OUT
    /usr/sbin/iptables -t mangle -A V2RAY_OUT  -m mark --mark 0xaa                              -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_OUT  -m addrtype --dst-type LOCAL,MULTICAST,BROADCAST -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_OUT  -d 10.0.0.0/8                                    -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_OUT  -d 10.4.10.0/23                                  -j RETURN
    /usr/sbin/iptables -t mangle -A V2RAY_OUT  -d 10.4.88.0/23                                  -j RETURN

    /usr/sbin/iptables -t mangle -A V2RAY_OUT  -p udp -j MARK --set-mark 0x01/0x01
    /usr/sbin/iptables -t mangle -A V2RAY_OUT  -p tcp -j MARK --set-mark 0x01/0x01
    /usr/sbin/iptables -t mangle -A OUTPUT -j V2RAY_OUT

    /usr/sbin/iptables -t mangle -N V2RAY_DIVERT
    /usr/sbin/iptables -t mangle -A V2RAY_DIVERT -j MARK --set-mark 0x01/0x01
    /usr/sbin/iptables -t mangle -A V2RAY_DIVERT -j ACCEPT
    /usr/sbin/iptables -t mangle -I PREROUTING -p tcp -m socket -j V2RAY_DIVERT
}

stop()
{
    /usr/sbin/ip route del ${IP_ROUTE}
    /usr/sbin/ip rule  del ${IP_RULE}
    /usr/sbin/iptables -t nat    -S | grep V2RAY | sed -e "s/-A/iptables -t nat -D/g"    | grep "\-D" | while read -r CMD; do ${CMD}; done
    /usr/sbin/iptables -t mangle -S | grep V2RAY | sed -e "s/-A/iptables -t mangle -D/g" | grep "\-D" | while read -r CMD; do ${CMD}; done
    /usr/sbin/iptables -t mangle -F V2RAY_PRE
    /usr/sbin/iptables -t mangle -X V2RAY_PRE
    /usr/sbin/iptables -t mangle -F V2RAY_OUT
    /usr/sbin/iptables -t mangle -X V2RAY_OUT
    /usr/sbin/iptables -t mangle -F V2RAY_DIVERT
    /usr/sbin/iptables -t mangle -X V2RAY_DIVERT
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 2
        start
        ;;
    *)
        ;;
esac
